language: php

php:
  - 7.1.9
  - nightly

env:
  - APP_DEBUG=false

before_script:
  - php artisan key:generate

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - vendor/bin/phpunit