language: php

php:
  - 7.1.9
  - nightly

before_script:
  - cp .env.travis .env
  - php artisan key:generate

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - vendor/bin/phpunit